### ISSUE TITLE
zip file

### ISSUE THREAD

**Issue by jeremyallenjacobson** [sci4ga/adopt-a-stream-georgia#3]
I downloaded the zip file in the scraped_dataset folder. It shows up as 132 bytes and can't be unzipped on multiple devices so seems to be broken somehow. For instance, on using unzip I get the error `unzip:  cannot find zipfile directory in one of adopt-a-stream-georgia-data.zip`. When I run in linux `file adopt-a-stream-georgia-data.zip` I get `ASCII text`.
Same for another zip file I checked in the exported_dataset folder.

**Comment by robclewley** [comment]
It's not broken, it's stored using Git's LFS. But I'm new to it and their documentation isn't very good, so I'm not sure whether you're supposed to take any special steps. Are you saying the zip files didn't populate correctly when you cloned the repo? Or did you download it manually from github?

https://docs.github.com/en/repositories/working-with-files/managing-large-files

It works for me when I navigate to it manually from https://github.com/sci4ga/adopt-a-stream-georgia/blob/main/scraped_dataset/ then click the "Download" button.

**Comment by jeremyallenjacobson** [comment]
I cloned the repo and tried to unzip the file on my local machine.

When I used the GitHub download button that worked fine and it showed up on my system as 3.8 megabytes.




Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: Robert Clewley ***@***.***>
Sent: Friday, January 28, 2022, 11:24 AM
To: sci4ga/adopt-a-stream-georgia
Cc: Jacobson, Jeremy; Author
Subject: [External] Re: [sci4ga/adopt-a-stream-georgia] zip file (Issue #3)


It's not broken, it's stored using Git's LFS. But I'm new to it and their documentation isn't very good, so I'm not sure whether you're supposed to take any special steps. Are you saying the zip files didn't populate correctly when you cloned the repo? Or did you download it manually from github?

https://docs.github.com/en/repositories/working-with-files/managing-large-files<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.github.com%2Fen%2Frepositories%2Fworking-with-files%2Fmanaging-large-files&data=04%7C01%7Cjeremy.a.jacobson%40emory.edu%7C52e2d76fd05344347ea708d9e27aaa82%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637789838761782851%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SLcSV2KsM4HoNB4pGw4mY4ploW3B10RpCPCZvQ3QYhQ%3D&reserved=0>

It works for me when I navigate to it manually from https://github.com/sci4ga/adopt-a-stream-georgia/blob/main/scraped_dataset/<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsci4ga%2Fadopt-a-stream-georgia%2Fblob%2Fmain%2Fscraped_dataset%2F&data=04%7C01%7Cjeremy.a.jacobson%40emory.edu%7C52e2d76fd05344347ea708d9e27aaa82%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637789838761782851%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rPb5%2FkvbZlFiPTjczMlZyz9BHjGRAio%2B6l5Kl%2FImocw%3D&reserved=0> then click the "Download" button.

—
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsci4ga%2Fadopt-a-stream-georgia%2Fissues%2F3%23issuecomment-1024378222&data=04%7C01%7Cjeremy.a.jacobson%40emory.edu%7C52e2d76fd05344347ea708d9e27aaa82%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637789838761782851%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=dT%2BrHmE8MFV3tv6Mn1xIayP%2BXu8rgPxs2OXX68rVeTQ%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFBCDWASFD2SESGTDRRAPK3UYK7L7ANCNFSM5NBFE3LQ&data=04%7C01%7Cjeremy.a.jacobson%40emory.edu%7C52e2d76fd05344347ea708d9e27aaa82%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637789838761782851%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=20L9dEIyLb4nNc4TOZHWhqgHBt6snNa3nHeTF%2BjSjRU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjeremy.a.jacobson%40emory.edu%7C52e2d76fd05344347ea708d9e27aaa82%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637789838761782851%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2BRhdRYR0eudFH6kmZ%2FBFJCOzFe3WdcjsWMWLr99xNfQ%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjeremy.a.jacobson%40emory.edu%7C52e2d76fd05344347ea708d9e27aaa82%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637789838761782851%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=uoUBzr9eDJ%2BWnTrIJTSv8x95eNWVyTSl5y6pb1J4Hxo%3D&reserved=0>.

**Comment by jeremyallenjacobson** [comment]
Thanks for the link to Git's LFS, I get it now 👍

**Comment by robclewley** [comment]
Well, I do want the files to be brought down automatically for people to use. Can you try running `git lfs pull`? If that complains about lfs, maybe you also have to install the LFS CLI, which is easy and described in the link I posted. I get the impression that we'll have to require users to install it, judging by posts like this: https://stackoverflow.com/questions/39691929/can-one-clone-a-git-lfs-repo-without-installing-git-lfs

**Comment by robclewley** [comment]
Fixed in https://github.com/sci4ga/adopt-a-stream-georgia/commit/b34dacc626347411061b6343c59553339448601d
